README.md

closed #3 
내용을 작성하고 이미지를 추가하였습니다.
리드미네이션 빠샤!!
없는데오...? 리드미 직접 봐요...

[#3] 중간과제를 위한 Readme 수정

---

Cardna-iOS/Cardna-iOS.xcodeproj/project.pbxproj
Cardna-iOS/Cardna-iOS/Source/AppSources/AppXibs/CardCollectionViewCell.swift
Cardna-iOS/Cardna-iOS/Source/AppSources/AppXibs/CardCollectionViewCell.xib

[#5] 카드셀 UI 만들기

---

Cardna-iOS/Cardna-iOS.xcodeproj/project.pbxproj
Cardna-iOS/Cardna-iOS/Configuration/AppExtensions/UIView+.swift

closed #9 
UIView에 레이아웃용 함수 하나 추가했어여
없음
없음.

[#9] UIView Extension 추가

---

Cardna-iOS/Cardna-iOS.xcodeproj/project.pbxproj
Cardna-iOS/Cardna-iOS/Source/Scene/Home/Extensions/HomeViewController+Extension.swift
Cardna-iOS/Cardna-iOS/Source/Scene/Home/Home.storyboard
Cardna-iOS/Cardna-iOS/Source/Scene/Home/HomeViewController.swift

closed #13 
- 홈 화면의 전체적인 UI를 구성해봤어요~
- 셀 내부 레이아웃, 색상이 카드나나 카드너로 바뀌는 부분은 서버 통신 이후 구현 예정!

[Feat] 홈화면 UI Pull Request

---

Cardna-iOS/Cardna-iOS.xcodeproj/project.pbxproj
Cardna-iOS/Cardna-iOS/Configuration/AppExtensions/String+.swift
Cardna-iOS/Cardna-iOS/Source/Scene/CardDetail/CardDetail.storyboard
Cardna-iOS/Cardna-iOS/Source/Scene/CardDetail/CardDetailViewController.swift

closed #22 
상세 뷰 UI
일단 내부 UI를 짰고
분기처리에 따른 버튼 유무, 색상, 아이콘 모양은 이후 구현 예정입니다!! 일단 UI만 봐주세요~

[Feat] 카드 상세뷰 UI

---

Cardna-iOS/Cardna-iOS.xcodeproj/project.pbxproj
Cardna-iOS/Cardna-iOS/Source/Scene/Card/Card.storyboard
Cardna-iOS/Cardna-iOS/Source/Scene/Card/CardViewController.swift
Cardna-iOS/Cardna-iOS/Source/Scene/Card/Cell/CardPackTitleCollectionViewCell.swift
Cardna-iOS/Cardna-iOS/Source/Scene/Card/Extensions/CardViewController+Extension.swift

closed #19 
카드팩 타이틀 간 이동시 indicator bar swipe 구현 완료
미니에서 살짝 이상한 이슈가 있는데 잘못된게 아닌거같다는 결론으로 일단 둡니다..
추후 바 이동은 비율로 계산해서 빨리 수정해놓을게염
스크린샷에선 바 이동이 느릿느릿 보이네요 ,, 실제로 보면 안느리답니다..

[#19] 카드팩 타이틀 간 이동시 indicator bar swipe 구현

---

Cardna-iOS/Cardna-iOS.xcodeproj/project.pbxproj
Cardna-iOS/Cardna-iOS/Source/Scene/Card/Card.storyboard
Cardna-iOS/Cardna-iOS/Source/Scene/Card/CardViewController.swift
Cardna-iOS/Cardna-iOS/Source/Scene/Card/Cell/CardContainerCollectionViewCell.swift
Cardna-iOS/Cardna-iOS/Source/Scene/Card/Extensions/CardViewController+Extension.swift

closed #20 
카드나/카드너 title과 카드내용 swipe 동기화 구현
그냥 넣어둔 빨간색 파란색은 안에 collectionView 또 넣으면서 지워질겁니닷~!
한 뷰 안에 컬렉션뷰가 세개가 필요해서 처리를 하느라 코드가 좀 복잡하게 보일거같네요..
견뎌
그리구 원래는 스크린샷보다 매끄럽습니다.. (gif 반성해)

[#20] 카드나/카드너 title과 카드내용 swipe 동기화 구현

---

Cardna-iOS/Cardna-iOS.xcodeproj/project.pbxproj
Cardna-iOS/Cardna-iOS/Source/Scene/SelectCard/Extensions/SelectCardViewController+Extension.swift
Cardna-iOS/Cardna-iOS/Source/Scene/SelectCard/SelectCard.storyboard
Cardna-iOS/Cardna-iOS/Source/Scene/SelectCard/SelectCardHeaderCollectionReusableView.swift
Cardna-iOS/Cardna-iOS/Source/Scene/SelectCard/SelectCardViewController.swift

[#26] 대표카드 수정 첫번째뷰 레이아웃

---

Cardna-iOS/Cardna-iOS.xcodeproj/project.pbxproj
Cardna-iOS/Cardna-iOS/Source/Scene/AddCard/AddCardBottomSheet.storyboard
Cardna-iOS/Cardna-iOS/Source/Scene/AddCard/AddCardBottomSheetViewController.swift
Cardna-iOS/Cardna-iOS/Source/Scene/AddCard/AddCardViewController.swift
Cardna-iOS/Cardna-iOS/Source/Scene/AddCard/Cell/AddCardSymbolCollectionViewCell.swift
Cardna-iOS/Cardna-iOS/Source/Scene/AddCard/Extensions/AddCardViewController+Extension.swift

closed #17
addCardBottomSheet 뷰의 UI를 완료하였습니다.
코드에서 냄새가 나요.... 날카로운 지적을 환영합니다.

[#17] addCardBottomSheet 뷰 UI 완료

---

Cardna-iOS/Cardna-iOS.xcodeproj/project.pbxproj
Cardna-iOS/Cardna-iOS/Source/Scene/SelectCard/Extensions/SelectCardModalViewController+Extension.swift
Cardna-iOS/Cardna-iOS/Source/Scene/SelectCard/SelectCard.storyboard
Cardna-iOS/Cardna-iOS/Source/Scene/SelectCard/SelectCardModalViewController.swift
Cardna-iOS/Cardna-iOS/Source/Scene/SelectCard/SelectCardViewController.swift

[#34] 대표카드 수정 두번째 뷰 UI

---

Cardna-iOS/Cardna-iOS.xcodeproj/project.pbxproj
Cardna-iOS/Cardna-iOS/Source/AppSources/AppXibs/ListTableViewCell.swift
Cardna-iOS/Cardna-iOS/Source/AppSources/AppXibs/ListTableViewCell.xib
Cardna-iOS/Cardna-iOS/Source/Scene/CardNotYetBox/CardNotYetBox.storyboard
Cardna-iOS/Cardna-iOS/Source/Scene/CardNotYetBox/CardNotYetBoxViewController.swift
Cardna-iOS/Cardna-iOS/Source/Scene/CardNotYetBox/Extensions/CardNotYetBoxViewController+Extension.swift

closed #36 
갤러리 아이콘 에셋 더 받고나서 바꿀예정

[#36] 타인이 말하는 나 뷰

---

Cardna-iOS/Cardna-iOS/Source/Scene/MyPageSetting/Cell/MyPageSettingTitleTableViewCell.swift
Cardna-iOS/Cardna-iOS/Source/Scene/MyPageSetting/Extensions/MyPageSettingViewController+Extension.swift
Cardna-iOS/Cardna-iOS/Source/Scene/MyPageSetting/MyPageSetting.storyboard
Cardna-iOS/Cardna-iOS/Source/Scene/MyPageSetting/MyPageSettingViewController.swift

closed #32 
MyPage 설정 뷰 UI 구현완료

[#32] MyPage 설정 뷰 UI 구현완

---

Cardna-iOS/Cardna-iOS/Source/Scene/Card/Card.storyboard
Cardna-iOS/Cardna-iOS/Source/Scene/Card/Cell/CardContainerCollectionViewCell.swift
Cardna-iOS/Cardna-iOS/Source/Scene/Card/Extensions/CardViewController+Extension.swift

closed #29 
카드팩 swipe 안에 collection view로 실제 카드팩 띄우기 구현 완료

[#29] 카드팩 swipe 안에 collection view로 실제 카드팩 띄우기 구현 완료

---

Cardna-iOS/Cardna-iOS.xcodeproj/project.pbxproj
Cardna-iOS/Cardna-iOS/Configuration/AppExtensions/UITextField+.swift
Cardna-iOS/Cardna-iOS/Source/Scene/EmailSearch/EmailSearch.storyboard
Cardna-iOS/Cardna-iOS/Source/Scene/EmailSearch/EmailSearchViewController.swift

closed #40 
이메일로 친구검색 구현 완 (+empty View 포함)

[#40] 이메일로 친구검색 구현 완 (+empty View 포함)

---

Cardna-iOS/Cardna-iOS.xcodeproj/project.pbxproj
Cardna-iOS/Cardna-iOS/Source/Scene/Initial/Initial.storyboard
Cardna-iOS/Cardna-iOS/Source/Scene/Initial/InitialViewController.swift

[#42] 이니셜 뷰 UI 구현 완료

---

Cardna-iOS/Cardna-iOS.xcodeproj/project.pbxproj
Cardna-iOS/Cardna-iOS/Source/AppSources/AppXibs/ProfileCollectionViewCell.swift
Cardna-iOS/Cardna-iOS/Source/AppSources/AppXibs/ProfileCollectionViewCell.xib
Cardna-iOS/Cardna-iOS/Source/Scene/MyPage/Cell/MyPageFriendsTableViewCell.swift
Cardna-iOS/Cardna-iOS/Source/Scene/MyPage/Cell/MyPageProfileTableViewCell.swift
Cardna-iOS/Cardna-iOS/Source/Scene/MyPage/Extensions/MyPageViewController+Extension.swift
Cardna-iOS/Cardna-iOS/Source/Scene/MyPage/MyPage.storyboard
Cardna-iOS/Cardna-iOS/Source/Scene/MyPage/MyPageViewController.swift

[#44] 마이페이지 메인

---

Cardna-iOS/Cardna-iOS.xcodeproj/project.pbxproj
Cardna-iOS/Cardna-iOS/Source/Scene/Join/JoinNameViewController.swift
Cardna-iOS/Cardna-iOS/Source/Scene/Join/JoinViewController.storyboard
Cardna-iOS/Cardna-iOS/Source/Scene/Join/JoinViewController.swift

closed #52 
회원가입 뷰의 UI만 만들었어오..

[#52] 회원가입 뷰 UI 구현

---

Cardna-iOS/Cardna-iOS/Source/AppSources/AppXibs/CardCollectionViewCell.swift
Cardna-iOS/Cardna-iOS/Source/AppSources/AppXibs/CardCollectionViewCell.xib
Cardna-iOS/Cardna-iOS/Source/Scene/Card/Cell/CardContainerCollectionViewCell.swift
Cardna-iOS/Cardna-iOS/Source/Scene/Home/Extensions/HomeViewController+Extension.swift
Cardna-iOS/Cardna-iOS/Source/Scene/SelectCard/Extensions/SelectCardModalViewController+Extension.swift
Cardna-iOS/Cardna-iOS/Source/Scene/SelectCard/Extensions/SelectCardViewController+Extension.swift

[#62] 카드셀 레이아웃 디테일 수정

---

Cardna-iOS/Cardna-iOS/Source/AppSources/AppXibs/CardCollectionViewCell.swift
Cardna-iOS/Cardna-iOS/Source/Scene/Home/Home.storyboard
Cardna-iOS/Cardna-iOS/Source/Scene/Home/HomeViewController.swift
Cardna-iOS/Cardna-iOS/Source/Scene/SelectCard/SelectCard.storyboard
Cardna-iOS/Cardna-iOS/Source/Scene/SelectCard/SelectCardHeaderCollectionReusableView.swift
Cardna-iOS/Cardna-iOS/Source/Scene/SelectCard/SelectCardViewController.swift

[#61] 홈 대표카드 UI수정

---

Cardna-iOS/Cardna-iOS.xcodeproj/project.pbxproj
Cardna-iOS/Cardna-iOS/Source/Scene/Login/Login.storyboard
Cardna-iOS/Cardna-iOS/Source/Scene/Login/LoginViewController.swift

[#56] 로그인뷰 UI 구현완료

---

Cardna-iOS/Cardna-iOS.xcodeproj/project.pbxproj
Cardna-iOS/Cardna-iOS/Configuration/AppExtensions/UIImageView+.swift
Cardna-iOS/Cardna-iOS/Source/AppSources/AppXibs/CardCollectionViewCell.swift
Cardna-iOS/Cardna-iOS/Source/Scene/Card/Cell/CardContainerCollectionViewCell.swift
Cardna-iOS/Cardna-iOS/Source/Scene/Home/Extensions/HomeViewController+Extension.swift
Cardna-iOS/Cardna-iOS/Source/Scene/Home/Home.storyboard
Cardna-iOS/Cardna-iOS/Source/Scene/Home/HomeViewController.swift
Cardna-iOS/Cardna-iOS/Source/Scene/SelectCard/Extensions/SelectCardModalViewController+Extension.swift
Cardna-iOS/Cardna-iOS/Source/Scene/SelectCard/Extensions/SelectCardViewController+Extension.swift

[#59] 대표카드 서버통신 후 UI반영

---

Cardna-iOS/Cardna-iOS/Network/APIModels/MyPageModel/MyPageResponse.swift
Cardna-iOS/Cardna-iOS/Network/APIServices/MyPageAPI/MyPageService.swift
Cardna-iOS/Cardna-iOS/Source/AppSources/AppXibs/ProfileCollectionViewCell.swift
Cardna-iOS/Cardna-iOS/Source/AppSources/AppXibs/ProfileCollectionViewCell.xib
Cardna-iOS/Cardna-iOS/Source/Scene/MyPage/Cell/MyPageFriendsTableViewCell.swift
Cardna-iOS/Cardna-iOS/Source/Scene/MyPage/Cell/MyPageProfileTableViewCell.swift
Cardna-iOS/Cardna-iOS/Source/Scene/MyPage/Extensions/MyPageViewController+Extension.swift
Cardna-iOS/Cardna-iOS/Source/Scene/MyPage/MyPage.storyboard
Cardna-iOS/Cardna-iOS/Source/Scene/MyPage/MyPageViewController.swift

[#60] 마이페이지 서버통신 완료

---

Cardna-iOS/Cardna-iOS.xcodeproj/project.pbxproj
Cardna-iOS/Cardna-iOS/Network/APIModels/LoginModel/LoginRequest.swift
Cardna-iOS/Cardna-iOS/Network/APIModels/LoginModel/LoginResponse.swift
Cardna-iOS/Cardna-iOS/Network/APIServices/LoginAPI/LoginRouter.swift
Cardna-iOS/Cardna-iOS/Network/APIServices/LoginAPI/LoginService.swift
Cardna-iOS/Cardna-iOS/Source/Scene/Login/Extension/LoginViewController+Extension.swift
Cardna-iOS/Cardna-iOS/Source/Scene/Login/Login.storyboard
Cardna-iOS/Cardna-iOS/Source/Scene/Login/LoginViewController.swift

closed #68 
로그인뷰 서버통신 완료
확인하려고 띄운 alert 등 필요 없는 것들은 로그인뷰 UI 고치면서 다 빼겠슴당~!

[#68] 로그인 서버연동 완료

---

Cardna-iOS/Cardna-iOS/Source/Scene/AddCard/AddCardViewController.swift
Cardna-iOS/Cardna-iOS/Source/Scene/AddCard/Extensions/AddCardViewController+Extension.swift

closed #27
카드나 작성 뷰의 keyword 글자수 제한 기능을 추가하였습니다.

[#27] 카드나 작성 뷰 keyword textField 글자수 제한 추가

---

Cardna-iOS/Cardna-iOS/Source/Scene/AddCard/AddCardCompletedViewController.swift

closed #50 
카드나 작성 완료 뷰의 Lottie를 추가하였습니다.

[#50] 카드나 작성 완료 뷰 Lottie 추가

---

Cardna-iOS/Cardna-iOS.xcodeproj/project.pbxproj
Cardna-iOS/Cardna-iOS/Network/APIModels/CardDetailModel/CardDetailResponse.swift
Cardna-iOS/Cardna-iOS/Network/APIServices/CardDetailAPI/CardDetailRouter.swift
Cardna-iOS/Cardna-iOS/Network/APIServices/CardDetailAPI/CardDetailService.swift
Cardna-iOS/Cardna-iOS/Source/Scene/CardDetail/CardDetail.storyboard
Cardna-iOS/Cardna-iOS/Source/Scene/CardDetail/CardDetailViewController.swift
Cardna-iOS/Cardna-iOS/Source/Scene/Home/Extensions/HomeViewController+Extension.swift
Cardna-iOS/Cardna-iOS/Source/Scene/Home/HomeViewController.swift

[#76] 대표카드 -> 카드상세 서버연결, id 전달

---

Cardna-iOS/Cardna-iOS/Network/APIServices/MainCardAPI/MainCardRouter.swift
Cardna-iOS/Cardna-iOS/Network/APIServices/MainCardAPI/MainCardService.swift
Cardna-iOS/Cardna-iOS/Source/Scene/Home/HomeViewController.swift
Cardna-iOS/Cardna-iOS/Source/Scene/SelectCard/Extensions/SelectCardViewController+Extension.swift
Cardna-iOS/Cardna-iOS/Source/Scene/SelectCard/SelectCard.storyboard
Cardna-iOS/Cardna-iOS/Source/Scene/SelectCard/SelectCardViewController.swift

[#83] 수정 서버통신 완료 (로직 구현 X)

---

Cardna-iOS/Cardna-iOS.xcodeproj/project.pbxproj
Cardna-iOS/Cardna-iOS/Network/APIModels/InsightModel/InsightResponse.swift
Cardna-iOS/Cardna-iOS/Network/APIServices/InsightAPI/InsightRouter.swift
Cardna-iOS/Cardna-iOS/Network/APIServices/InsightAPI/InsightService.swift
Cardna-iOS/Cardna-iOS/Source/Scene/Insight/Extensions/InsightViewController+Extension.swift
Cardna-iOS/Cardna-iOS/Source/Scene/Insight/InsightViewController.swift

[#64] insight 서버통신 완료

---

Cardna-iOS/Cardna-iOS.xcodeproj/project.pbxproj
Cardna-iOS/Cardna-iOS/Network/APIModels/AddCardModel/AddCardRequest.swift
Cardna-iOS/Cardna-iOS/Network/APIServices/AddCardAPI/AddCardService.swift
Cardna-iOS/Cardna-iOS/Source/Scene/AddCard/AddCardViewController.swift

closed #81 
카드나 작성 뷰의 서버연결을 완료하였습니다~

[#81] 카드나 작성 뷰 서버연결 완료

---

Cardna-iOS/Cardna-iOS/Network/APIModels/EmailSearchModel/EmailSearchResponse.swift
Cardna-iOS/Cardna-iOS/Network/APIServices/EmailSearchAPI/EmailSearchRouter.swift
Cardna-iOS/Cardna-iOS/Network/APIServices/EmailSearchAPI/EmailSearchService.swift
Cardna-iOS/Cardna-iOS/Source/Scene/EmailSearch/EmailSearch.storyboard
Cardna-iOS/Cardna-iOS/Source/Scene/EmailSearch/EmailSearchViewController.swift
Cardna-iOS/Cardna-iOS/Source/Scene/EmailSearch/Extensions/EmailSearchViewController+Extension.swift

[#77] 이메일로 친구 검색 서버 연결

---

Cardna-iOS/Cardna-iOS/Network/APIModels/CardPackModel/CardPackResponse.swift
Cardna-iOS/Cardna-iOS/Network/APIServices/CardPackAPI/CardPackRouter.swift
Cardna-iOS/Cardna-iOS/Network/APIServices/CardPackAPI/CardPackService.swift
Cardna-iOS/Cardna-iOS/Source/AppSources/AppXibs/CardCollectionViewCell.swift
Cardna-iOS/Cardna-iOS/Source/AppSources/AppXibs/CardCollectionViewCell.xib
Cardna-iOS/Cardna-iOS/Source/Scene/SelectCard/Extensions/SelectCardModalViewController+Extension.swift
Cardna-iOS/Cardna-iOS/Source/Scene/SelectCard/SelectCard.storyboard
Cardna-iOS/Cardna-iOS/Source/Scene/SelectCard/SelectCardModalViewController.swift
Cardna-iOS/Cardna-iOS/Source/Scene/SelectCard/SelectCardViewController.swift

[#85] 카드선택 카드나,카드너 조회

---

Cardna-iOS/Cardna-iOS/Source/Scene/Initial/Initial.storyboard
Cardna-iOS/Cardna-iOS/Source/Scene/Initial/InitialViewController.swift
Cardna-iOS/Cardna-iOS/Source/Scene/Join/JoinViewController.storyboard
Cardna-iOS/Cardna-iOS/Source/Scene/Login/Login.storyboard

closed #96 
initial view 화면전환 구현 완료

[#96] initial view 화면전환 구현 완료

---

Cardna-iOS/Cardna-iOS/Source/Scene/SelectCard/Extensions/SelectCardModalViewController+Extension.swift
Cardna-iOS/Cardna-iOS/Source/Scene/SelectCard/Extensions/SelectCardViewController+Extension.swift
Cardna-iOS/Cardna-iOS/Source/Scene/SelectCard/SelectCard.storyboard
Cardna-iOS/Cardna-iOS/Source/Scene/SelectCard/SelectCardModalViewController.swift
Cardna-iOS/Cardna-iOS/Source/Scene/SelectCard/SelectCardViewController.swift

[#99] 대표카드 수정 카드 가져와서 첫화면에 보여줌

---

Cardna-iOS/Cardna-iOS/Configuration/Constants/Image.swift
Cardna-iOS/Cardna-iOS/Source/Scene/EmailSearch/EmailSearch.storyboard
Cardna-iOS/Cardna-iOS/Source/Scene/EmailSearch/EmailSearchViewController.swift

closed #78 
이메일 친구 검색시 버튼 UI 토글 구현 + 에셋 상수 추가

[#78] 이메일 친구 검색시 버튼 UI 토글 구현 + 에셋 상수 추가

---

Cardna-iOS/Cardna-iOS/Source/Scene/SelectCard/SelectCardViewController.swift

[#101] 대표카드 서버연결 후 반영

---

Cardna-iOS/Cardna-iOS/Source/Scene/EmailSearch/EmailSearch.storyboard
Cardna-iOS/Cardna-iOS/Source/Scene/EmailSearch/EmailSearchViewController.swift
Cardna-iOS/Cardna-iOS/Source/Scene/EmailSearch/Extensions/EmailSearchViewController+Extension.swift

closed #94 
이메일 검색 실패했을시 화면 처리

[#94] 이메일 검색 실패했을시 화면 처리

---

Cardna-iOS/Cardna-iOS/Network/APIModels/AddFriendModel/AddFriendRequest.swift
Cardna-iOS/Cardna-iOS/Network/APIModels/AddFriendModel/AddFriendResponse.swift
Cardna-iOS/Cardna-iOS/Network/APIServices/AddFriendAPI/AddFriendRouter.swift
Cardna-iOS/Cardna-iOS/Network/APIServices/AddFriendAPI/AddFriendService.swift
Cardna-iOS/Cardna-iOS/Source/Scene/EmailSearch/EmailSearchViewController.swift
Cardna-iOS/Cardna-iOS/Source/Scene/EmailSearch/Extensions/EmailSearchViewController+Extension.swift

closed #98 
이메일로 검색해서 친구 추가/삭제 서버 연결 완료

[#98] 이메일로 검색해서 친구 추가/삭제 서버 연결 완료

---

Cardna-iOS/Cardna-iOS/Network/APIServices/EmailSearchAPI/EmailSearchService.swift
Cardna-iOS/Cardna-iOS/Source/Scene/EmailSearch/EmailSearchViewController.swift
Cardna-iOS/Cardna-iOS/Source/Scene/EmailSearch/Extensions/EmailSearchViewController+Extension.swift

closed #103 
이메일 존재하지 않을 시 화면 전환 자세히 구현

[#103] 이메일 존재하지 않을 시 화면 전환 자세히 구현

---

Cardna-iOS/Cardna-iOS/Source/Scene/Insight/Insight.storyboard
Cardna-iOS/Cardna-iOS/Source/Scene/Insight/InsightViewController.swift

closed #87 
인사이트 카드 nil시 뷰와 서버통신 처리 구현
서버와 재확인 필요

[#87] 인사이트 카드 nil시 뷰와 서버통신 처리 구현

---

Cardna-iOS/Cardna-iOS/Network/APIModels/CardPackModel/CardPackResponse.swift
Cardna-iOS/Cardna-iOS/Source/AppSources/AppXibs/CardCollectionViewCell.swift
Cardna-iOS/Cardna-iOS/Source/AppSources/AppXibs/CardCollectionViewCell.xib
Cardna-iOS/Cardna-iOS/Source/Scene/Home/HomeViewController.swift
Cardna-iOS/Cardna-iOS/Source/Scene/SelectCard/Extensions/SelectCardModalViewController+Extension.swift
Cardna-iOS/Cardna-iOS/Source/Scene/SelectCard/Extensions/SelectCardViewController+Extension.swift
Cardna-iOS/Cardna-iOS/Source/Scene/SelectCard/SelectCardViewController.swift

[#111] 대표카드 선택 숫자 Count

---

Cardna-iOS/Cardna-iOS.xcodeproj/project.pbxproj
Cardna-iOS/Cardna-iOS/Source/Scene/AddCard/AddCardBottomSheetViewController.swift
Cardna-iOS/Cardna-iOS/Source/Scene/AddCard/AddCardCompletedViewController.swift
Cardna-iOS/Cardna-iOS/Source/Scene/AddCard/AddCardViewController.swift
Cardna-iOS/Cardna-iOS/Source/Scene/AddCard/AddCardYouCompleted.storyboard
Cardna-iOS/Cardna-iOS/Source/Scene/AddCard/AddCardYouCompletedViewController.swift
Cardna-iOS/Cardna-iOS/Source/Scene/AddCard/AddCardYouViewController.storyboard
Cardna-iOS/Cardna-iOS/Source/Scene/AddCard/AddCardYouViewController.swift
Cardna-iOS/Cardna-iOS/Source/Scene/AddCard/Cell/AddCardSymbolCollectionViewCell.swift
Cardna-iOS/Cardna-iOS/Source/Scene/AddCard/Extensions/AddCardBottomSheetViewController+Extension.swift
Cardna-iOS/Cardna-iOS/Source/Scene/AddCard/Extensions/AddCardViewController+Extension.swift
Cardna-iOS/Cardna-iOS/Source/Scene/Card/CardBottomSheetViewController.swift
Cardna-iOS/Cardna-iOS/Source/Scene/Join/JoinViewController.storyboard

#90 
카드나/카드너 작성 뷰의 bottom sheet 심볼 선택 부분 로직 구현을 완료하였습니다.
코드에서 냄새가 나요.....

[#90] 카드나/카드너 작성 뷰 bottom sheet 심볼 선택 구현 완료

---

Cardna-iOS/Cardna-iOS/Source/AppSources/AppXibs/CardCollectionViewCell.swift
Cardna-iOS/Cardna-iOS/Source/AppSources/AppXibs/CardCollectionViewCell.xib
Cardna-iOS/Cardna-iOS/Source/Scene/SelectCard/Extensions/SelectCardModalViewController+Extension.swift
Cardna-iOS/Cardna-iOS/Source/Scene/SelectCard/SelectCard.storyboard
Cardna-iOS/Cardna-iOS/Source/Scene/SelectCard/SelectCardModalViewController.swift

[#113] 대표카드 수정 뷰 Modal 디테일 추가

---

Cardna-iOS/Cardna-iOS/Source/Scene/CardNotYetBox/CardNotYetBox.storyboard
Cardna-iOS/Cardna-iOS/Source/Scene/CardNotYetBox/CardNotYetBoxViewController.swift
Cardna-iOS/Cardna-iOS/Source/Scene/EmailSearch/EmailSearch.storyboard
Cardna-iOS/Cardna-iOS/Source/Scene/MyPage/Extensions/MyPageViewController+Extension.swift
Cardna-iOS/Cardna-iOS/Source/Scene/MyPage/MyPage.storyboard
Cardna-iOS/Cardna-iOS/Source/Scene/MyPage/MyPageViewController.swift

[#116] 마이페이지 디테일 잡기

---

Cardna-iOS/Cardna-iOS/Source/Scene/EmailSearch/EmailSearch.storyboard
Cardna-iOS/Cardna-iOS/Source/Scene/EmailSearch/EmailSearchViewController.swift

closed #93 
backButton 눌렀을 때 화면 전환 완료했습니다

[#93] backButton 화면전환 완료

---

Cardna-iOS/Cardna-iOS/Network/APIServices/InsightAPI/InsightService.swift

closed #119 
insight view 카드 없는 상황 서버처리, empty view처리 구현
테스트는 아무 카드도 없는 솔 토큰으로 해봤어요~!

[#119] insight view 카드 없는 상황 서버처리, empty view처리 구현

---

Cardna-iOS/Cardna-iOS/Configuration/AppExtensions/UIViewController+.swift
Cardna-iOS/Cardna-iOS/Source/Scene/EmailSearch/EmailSearchViewController.swift

closed #91 
이메일 검색을 통한 친구 추가 시 토스트 메세지 + 토스트 시간 조정하였습니다

[#91] 이메일 검색을 통한 친구 추가 시 토스트 메세지 + 토스트 시간 조정

---

Cardna-iOS/Cardna-iOS/Source/Scene/Login/Login.storyboard
Cardna-iOS/Cardna-iOS/Source/Scene/Login/LoginViewController.swift

closed #121 
로그인 뷰 backButton 화면전환 완료

[#121] 로그인 뷰 backButton 화면전환 완료

---

Cardna-iOS/Cardna-iOS/Network/APIServices/MainCardAPI/MainCardRouter.swift
Cardna-iOS/Cardna-iOS/Network/APIServices/MainCardAPI/MainCardService.swift
Cardna-iOS/Cardna-iOS/Source/Scene/Home/HomeViewController.swift
Cardna-iOS/Cardna-iOS/Source/Scene/MyPage/Cell/MyPageFriendsTableViewCell.swift
Cardna-iOS/Cardna-iOS/Source/Scene/MyPage/Extensions/MyPageViewController+Extension.swift

[#118] 마이페이지 -> 친구의 대표카드 화면전환 및 서버연결

---

Cardna-iOS/Cardna-iOS/Configuration/AppExtensions/UIColor+.swift
Cardna-iOS/Cardna-iOS/Source/Scene/Home/Extensions/HomeViewController+Extension.swift
Cardna-iOS/Cardna-iOS/Source/Scene/Home/Home.storyboard
Cardna-iOS/Cardna-iOS/Source/Scene/Home/HomeViewController.swift
Cardna-iOS/Cardna-iOS/Source/Scene/MyPage/Cell/MyPageFriendsTableViewCell.swift
Cardna-iOS/Cardna-iOS/Source/Scene/MyPage/Extensions/MyPageViewController+Extension.swift

closed #135 
이름 (본인이름은 로그인에서 userdefault에 저장하는 방법으로 해야할듯여)
밑줄
카운트 완료

[#135] 이름, 밑줄, 카드 count 추가

---

Cardna-iOS/Cardna-iOS/Configuration/AppExtensions/UIColor+.swift
Cardna-iOS/Cardna-iOS/Source/Scene/CardDetail/CardDetail.storyboard
Cardna-iOS/Cardna-iOS/Source/Scene/CardDetail/CardDetailViewController.swift
Cardna-iOS/Cardna-iOS/Source/Scene/Home/Extensions/HomeViewController+Extension.swift
Cardna-iOS/Cardna-iOS/Source/Scene/Home/HomeViewController.swift

[#137] 카드상세뷰 카드나/카드너 분기처리 완료

---

Cardna-iOS/Cardna-iOS/Source/Scene/EmailSearch/EmailSearch.storyboard
Cardna-iOS/Cardna-iOS/Source/Scene/EmailSearch/EmailSearchViewController.swift

closed #122 
이메일로 검색 결과 화면 구현방식 수정

[#122] 이메일로 검색 결과 화면 구현방식 수정

---

Cardna-iOS/Cardna-iOS/Network/APIModels/CardPackModel/CardPackResponse.swift
Cardna-iOS/Cardna-iOS/Network/APIServices/CardPackAPI/CardPackRouter.swift
Cardna-iOS/Cardna-iOS/Network/APIServices/CardPackAPI/CardPackService.swift
Cardna-iOS/Cardna-iOS/Source/Scene/CardNotYetBox/CardNotYetBoxViewController.swift
Cardna-iOS/Cardna-iOS/Source/Scene/CardNotYetBox/Extensions/CardNotYetBoxViewController+Extension.swift

[#138] 카드 보관함 서버연결

---

Cardna-iOS/Cardna-iOS/Network/APIModels/CardPackModel/CardPackResponse.swift
Cardna-iOS/Cardna-iOS/Network/APIServices/CardPackAPI/CardPackRouter.swift
Cardna-iOS/Cardna-iOS/Network/APIServices/CardPackAPI/CardPackService.swift
Cardna-iOS/Cardna-iOS/Source/Scene/CardDetail/CardDetail.storyboard
Cardna-iOS/Cardna-iOS/Source/Scene/CardDetail/CardDetailViewController.swift
Cardna-iOS/Cardna-iOS/Source/Scene/CardNotYetBox/CardNotYetBox.storyboard
Cardna-iOS/Cardna-iOS/Source/Scene/CardNotYetBox/CardNotYetBoxViewController.swift
Cardna-iOS/Cardna-iOS/Source/Scene/CardNotYetBox/Extensions/CardNotYetBoxViewController+Extension.swift
Cardna-iOS/Cardna-iOS/Source/Scene/MyPage/MyPageViewController.swift

[#140] 카드너만들기 서버연결

---

Cardna-iOS/Cardna-iOS/Source/Scene/AddCard/AddCardBottomSheet.storyboard
Cardna-iOS/Cardna-iOS/Source/Scene/AddCard/AddCardBottomSheetViewController.swift
Cardna-iOS/Cardna-iOS/Source/Scene/AddCard/AddCardCompletedViewController.swift
Cardna-iOS/Cardna-iOS/Source/Scene/AddCard/Extensions/AddCardViewController+Extension.swift

closed #90 
bottom sheet의 모양에 따른 기본 이미지 세팅 작업을 완료하였습니다.
이번에도 코드에서 냄새가 나네요..

[#90] 카드나/카드너 작성 뷰 분기 처리 완료

---

Cardna-iOS/Cardna-iOS/Source/Scene/CardDetail/CardDetail.storyboard
Cardna-iOS/Cardna-iOS/Source/Scene/CardDetail/CardDetailViewController.swift
Cardna-iOS/Cardna-iOS/Source/Scene/CardNotYetBox/CardNotYetBox.storyboard
Cardna-iOS/Cardna-iOS/Source/Scene/Home/HomeViewController.swift

[#144] 카드너->보관 완료

---

Cardna-iOS/Cardna-iOS/Source/Scene/Insight/InsightViewController.swift

closed #128 
Insight view 카드 조회 결과 구현방식 수정

[#128] Insight view 카드 조회 결과 구현방식 수정

---

Cardna-iOS/Cardna-iOS/Source/Scene/CardDetail/CardDetail.storyboard
Cardna-iOS/Cardna-iOS/Source/Scene/CardDetail/CardDetailViewController.swift

[#151] 카드상세 분기처리 및 menu띄우기

---

Cardna-iOS/Cardna-iOS/Network/APIModels/InsightModel/InsightResponse.swift
Cardna-iOS/Cardna-iOS/Source/Scene/Insight/InsightViewController.swift

closed #150 
Insight 카드 하나만 있을 때 서버 처리 완료

[#150] Insight 카드 하나만 있을 때 서버 처리 완료

---

Cardna-iOS/Cardna-iOS/Source/Scene/MyPage/Cell/MyPageFriendsTableViewCell.swift
Cardna-iOS/Cardna-iOS/Source/Scene/MyPage/Extensions/MyPageViewController+Extension.swift
Cardna-iOS/Cardna-iOS/Source/Scene/MyPage/MyPageViewController.swift

[#154] 마이페이지 친구검색

---

Cardna-iOS/Cardna-iOS/Source/Scene/Card/CardViewController.swift

closed #159 
카드팩 재사용 변수 초기화, 친구 이름 데이터 전달용 함수 세팅

[#159] 카드팩 재사용 변수 초기화, 친구 이름 데이터 전달용 함수 세팅

---

Cardna-iOS/Cardna-iOS/Configuration/AppExtensions/UIViewController+.swift
Cardna-iOS/Cardna-iOS/Network/APIModels/CardPackModel/CardPackResponse.swift
Cardna-iOS/Cardna-iOS/Network/APIServices/CardPackAPI/CardPackRouter.swift
Cardna-iOS/Cardna-iOS/Network/APIServices/CardPackAPI/CardPackService.swift
Cardna-iOS/Cardna-iOS/Source/Scene/CardDetail/CardDetailViewController.swift

[#161] 카드삭제 구현

---

Cardna-iOS/Cardna-iOS/Network/APIModels/CardDetailModel/CardDetailResponse.swift
Cardna-iOS/Cardna-iOS/Network/APIServices/CardDetailAPI/CardDetailService.swift
Cardna-iOS/Cardna-iOS/Source/Scene/CardDetail/CardDetail.storyboard
Cardna-iOS/Cardna-iOS/Source/Scene/CardDetail/CardDetailViewController.swift
Cardna-iOS/Cardna-iOS/Source/Scene/Home/Extensions/HomeViewController+Extension.swift
Cardna-iOS/Cardna-iOS/Source/Scene/Home/HomeViewController.swift

[#164] 타인의 카드 상세 디테일

---

Cardna-iOS/Cardna-iOS/Source/Scene/Initial/Initial.storyboard

closed #123 
Initial view (진입) 기기대응 layout 수정

[#123] Initial view (진입) 기기대응 layout 수정

---

Cardna-iOS/Cardna-iOS/Source/AppSources/AppXibs/CardCollectionViewCell.swift
Cardna-iOS/Cardna-iOS/Source/AppSources/AppXibs/CardCollectionViewCell.xib
Cardna-iOS/Cardna-iOS/Source/Scene/MyPage/MyPage.storyboard
Cardna-iOS/Cardna-iOS/Source/Scene/SelectCard/Extensions/SelectCardViewController+Extension.swift

[#170] 대표카드 수정에 뱃지 추가

---

Cardna-iOS/Cardna-iOS/Source/Scene/MainTabBarController.swift

[#172] 하단 탭바 그라데이션 추가

---

Cardna-iOS/Cardna-iOS/Source/Scene/Insight/InsightViewController.swift

closed #176 
insight view 진입 시 마다 scroll 위치 맨 처음으로 조정 완료

[#176] insight view 진입 시 마다 scroll 위치 맨 처음으로 조정 완료

---

Cardna-iOS/Cardna-iOS/Source/Scene/CardDetail/CardDetail.storyboard
Cardna-iOS/Cardna-iOS/Source/Scene/CardDetail/CardDetailViewController.swift

[#177] 카드상세뷰 레이아웃(se, mini, pro)

---

Cardna-iOS/Cardna-iOS/Source/Scene/Card/Card.storyboard
Cardna-iOS/Cardna-iOS/Source/Scene/Card/Cell/CardContainerCollectionViewCell.swift
Cardna-iOS/Cardna-iOS/Source/Scene/Card/Extensions/CardViewController+Extension.swift

closed #70 
카드팩 뷰 셀 레이아웃 조정 완료
esanghaeSEA 고맙습니다 !

[#70] 카드팩 뷰 셀 레이아웃 조정 완료

---

Cardna-iOS/Cardna-iOS/Configuration/Supports/AppDelegate.swift

[#189] IQKeyboardManagerSwift 설정

---

Cardna-iOS/Cardna-iOS/Source/AppSources/AppXibs/ListTableViewCell.xib
Cardna-iOS/Cardna-iOS/Source/Scene/CardNotYetBox/CardNotYetBox.storyboard
Cardna-iOS/Cardna-iOS/Source/Scene/MyPage/MyPage.storyboard
Cardna-iOS/Cardna-iOS/Source/Scene/MyPage/MyPageViewController.swift

[#191] 마이페이지, 보관함 테이블뷰 구분선 수정

---

Cardna-iOS/Cardna-iOS/Source/Scene/MyPage/MyPageViewController.swift
Cardna-iOS/Cardna-iOS/Source/Scene/SelectCard/SelectCardHeaderCollectionReusableView.swift

[#194] 이메일 추가 후 친구목록 reload

---

Cardna-iOS/Cardna-iOS/Network/APIServices/CardPackAPI/CardPackRouter.swift
Cardna-iOS/Cardna-iOS/Network/Base/URLConstant.swift
Cardna-iOS/Cardna-iOS/Source/Scene/Card/CardViewController.swift
Cardna-iOS/Cardna-iOS/Source/Scene/Card/Cell/CardContainerCollectionViewCell.swift
Cardna-iOS/Cardna-iOS/Source/Scene/Card/Extensions/CardViewController+Extension.swift

[#183] 카드팩 서버 연결 완료

---

Cardna-iOS/Cardna-iOS/Network/APIServices/CardPackAPI/CardPackRouter.swift
Cardna-iOS/Cardna-iOS/Source/Scene/Card/CardViewController.swift
Cardna-iOS/Cardna-iOS/Source/Scene/Home/Home.storyboard
Cardna-iOS/Cardna-iOS/Source/Scene/Home/HomeViewController.swift

closed #184 
친구 카드팩 보기 화면전환 연결 완료

[#184] 친구 카드팩 보기 화면전환 연결 완료

---

Cardna-iOS/Cardna-iOS/Source/Scene/CardDetail/CardDetail.storyboard
Cardna-iOS/Cardna-iOS/Source/Scene/CardDetail/CardDetailViewController.swift

[#197] 보라색 좋아요 로티 추가

---

Cardna-iOS/Cardna-iOS/Network/APIModels/AddCardModel/AddCardRequest.swift
Cardna-iOS/Cardna-iOS/Network/APIServices/AddCardAPI/AddCardService.swift
Cardna-iOS/Cardna-iOS/Source/Scene/AddCard/AddCardBottomSheetViewController.swift
Cardna-iOS/Cardna-iOS/Source/Scene/AddCard/AddCardViewController.swift

#148 
카드너 타인 소개 작성 뷰의 서버 연결 작업을 진행하였습니다.
아직 서버 응답에 대한 예외처리가 남아있습니다.

[#148] 카드너 타인 소개 작성 뷰의 서버 연결 작업 (예외처리 X)

---

Cardna-iOS/Cardna-iOS/Source/Scene/Home/Home.storyboard
Cardna-iOS/Cardna-iOS/Source/Scene/Home/HomeViewController.swift

[#202] 타인의 대표카드 뷰 ui

---

Cardna-iOS/Cardna-iOS/Configuration/AppExtensions/UIViewController+.swift
Cardna-iOS/Cardna-iOS/Info.plist
Cardna-iOS/Cardna-iOS/Network/Base/NetworkConstant.swift
Cardna-iOS/Cardna-iOS/Source/Scene/Home/HomeViewController.swift
Cardna-iOS/Cardna-iOS/Source/Scene/Login/Extension/LoginViewController+Extension.swift

[#205] 로그인 플로우

---

Cardna-iOS/Cardna-iOS.xcodeproj/project.pbxproj
Cardna-iOS/Cardna-iOS/Network/APIModels/JoinModel/JoinRequest.swift
Cardna-iOS/Cardna-iOS/Network/APIModels/JoinModel/JoinResponse.swift
Cardna-iOS/Cardna-iOS/Network/APIServices/JoinAPI/JoinRouter.swift
Cardna-iOS/Cardna-iOS/Network/APIServices/JoinAPI/JoinService.swift
Cardna-iOS/Cardna-iOS/Source/Scene/Join/Extension/JoinNameViewController+Extension.swift
Cardna-iOS/Cardna-iOS/Source/Scene/Join/JoinNameViewController.swift
Cardna-iOS/Cardna-iOS/Source/Scene/Join/JoinViewController.storyboard
Cardna-iOS/Cardna-iOS/Source/Scene/Join/JoinViewController.swift

closed #109 
회원가입 뷰 서버 연결 작업을 완료하였습니다.

[#109] 회원가입 뷰 서버 연결 작업

---

Cardna-iOS/Cardna-iOS/Source/Scene/Card/Card.storyboard

closed #212 
scroll view indicator bar 없앴습니다.

[#212] scroll view indicator bar 없애기

---

Cardna-iOS/Cardna-iOS/Source/AppSources/AppXibs/CardCollectionViewCell.swift
Cardna-iOS/Cardna-iOS/Source/AppSources/AppXibs/CardCollectionViewCell.xib

[#212] 카드셀 textColor 수정

---

Cardna-iOS/Cardna-iOS/Source/Scene/Insight/Insight.storyboard
Cardna-iOS/Cardna-iOS/Source/Scene/Insight/InsightViewController.swift

[#212] Insight empty view 수정사항 반영

---

Cardna-iOS/Cardna-iOS/Source/Scene/AddCard/AddCardYouViewController.swift
Cardna-iOS/Cardna-iOS/Source/Scene/Card/CardViewController.swift

closed #216 
친구 카드팩 버튼 IBAction 연결 완료

[#216] 친구 카드팩 버튼 IBAction 연결 완료

---

Cardna-iOS/Cardna-iOS.xcodeproj/project.pbxproj
Cardna-iOS/Cardna-iOS/Source/Scene/Initial/Initial.storyboard
Cardna-iOS/Cardna-iOS/Source/Scene/Initial/InitialNavigationViewController.swift
Cardna-iOS/Cardna-iOS/Source/Scene/MyPageSetting/Extensions/MyPageSettingViewController+Extension.swift

[#212] 로그아웃 하고 다시 이니셜뷰로 돌아가기

---

Cardna-iOS/Cardna-iOS/Source/Scene/CardNotYetBox/CardNotYetBox.storyboard
Cardna-iOS/Cardna-iOS/Source/Scene/CardNotYetBox/CardNotYetBoxViewController.swift

[#130] 타인이 말하는 나 화면전환 수정

---

Cardna-iOS/Cardna-iOS/Source/Scene/AddCard/AddCardViewController.swift

closed #217 
카드나/카드너 작성 뷰 AutoLayout 설정하였습니다.

[#217] 카드나/카드너 작성 뷰 AutoLayout 설정

---

Cardna-iOS/Cardna-iOS/Source/Scene/MyPage/Extensions/MyPageViewController+Extension.swift

[#226] 마이페이지 친구 없을때 튕기는 문제 해결

---

Cardna-iOS/Cardna-iOS/Source/Scene/AddCard/AddCardViewController.swift
Cardna-iOS/Cardna-iOS/Source/Scene/AddCard/AddCardYouViewController.storyboard
Cardna-iOS/Cardna-iOS/Source/Scene/AddCard/AddCardYouViewController.swift
Cardna-iOS/Cardna-iOS/Source/Scene/Join/JoinViewController.storyboard

closed #235 
textField border를 제거하였습니다.
(모든 textField의 border style을 `.none`으로 지정하고, height값을 지정하였습니다.

[#235] textField border 제거

---

Cardna-iOS/Cardna-iOS/Source/Scene/Initial/InitialViewController.swift
Cardna-iOS/Cardna-iOS/Source/Scene/Join/JoinNameViewController.swift

#57 
- 회원가입 뷰의 이름 입력에서 뒤로 뷰 하나만 pop하기
- swipe해서 뒤로가기 기능 추가

[#57] swipe해서 뒤로가기 추가, 회원가입뷰의 이름입력에서 뒤로 뷰 하나만 pop 수정

---

Cardna-iOS/Cardna-iOS/Source/Scene/Home/Home.storyboard
Cardna-iOS/Cardna-iOS/Source/Scene/Home/HomeViewController.swift

[#236] 친구 대표카드 뒤로가기 추가

---

Cardna-iOS/Cardna-iOS/Source/Scene/Login/Login.storyboard
Cardna-iOS/Cardna-iOS/Source/Scene/Login/LoginViewController.swift

[#230] 비밀번호 찾기 버튼 준비중이라고 하기

---

Cardna-iOS/Cardna-iOS/Source/Scene/Card/Card.storyboard
Cardna-iOS/Cardna-iOS/Source/Scene/Card/CardViewController.swift
Cardna-iOS/Cardna-iOS/Source/Scene/Card/Extensions/CardViewController+Extension.swift

[#243] 삭제 후 카드팩 리로드

---

Cardna-iOS/Cardna-iOS/Source/Scene/MyPageSetting/Extensions/MyPageSettingViewController+Extension.swift
Cardna-iOS/Cardna-iOS/Source/Scene/MyPageSetting/MyPageSetting.storyboard
Cardna-iOS/Cardna-iOS/Source/Scene/MyPageSetting/MyPageSettingRules.storyboard
Cardna-iOS/Cardna-iOS/Source/Scene/MyPageSetting/MyPageSettingRulesViewController.swift
Cardna-iOS/Cardna-iOS/Source/Scene/MyPageSetting/MyPageSettingViewController.swift

[#187] 설정뷰 버튼 처리

---

Cardna-iOS/Cardna-iOS/Source/Scene/CardDetail/CardDetail.storyboard
Cardna-iOS/Cardna-iOS/Source/Scene/CardDetail/CardDetailViewController.swift

[#246] 카드 상세페이지 from 수정

---

Cardna-iOS/Cardna-iOS/Source/Scene/CardDetail/CardDetailViewController.swift
Cardna-iOS/Cardna-iOS/Source/Scene/Login/Login.storyboard

closed #248 
로그인 textfield auto어쩌고도 바꿔줫음다.

[#248] 좋아요 로티 분기처리 및 보라색 추가

---

Cardna-iOS/Cardna-iOS/Source/Scene/SelectCard/Extensions/SelectCardModalViewController+Extension.swift
Cardna-iOS/Cardna-iOS/Source/Scene/SelectCard/SelectCardModalViewController.swift

[#250] 대표카드 로직 수정(두번째 수정도 인덱스 체크 잘 되도록 수정)

---

Cardna-iOS/Cardna-iOS/Source/Scene/SelectCard/Extensions/SelectCardViewController+Extension.swift
Cardna-iOS/Cardna-iOS/Source/Scene/SelectCard/SelectCardViewController.swift

[#252] 대표카드 첫번째 뷰 카운트

---

Cardna-iOS/Cardna-iOS/Source/Scene/Home/HomeViewController.swift

[#254] 대표카드 0개로 만든 후 라벨 사라지게 , 대표카드 추가하면 다시 나타나게

---

Cardna-iOS/Cardna-iOS/Source/Scene/Card/CardViewController.swift

[#256] 친구 카드팩 reload 오류 해결

---

Cardna-iOS/Cardna-iOS/Source/Scene/AddCard/AddCardViewController.swift
Cardna-iOS/Cardna-iOS/Source/Scene/Card/Card.storyboard
Cardna-iOS/Cardna-iOS/Source/Scene/SelectCard/SelectCard.storyboard

[#258] 사진없을 때 카드너 추가 터지는 오류 수정, 카드팩 기본 숫자 변경

---

Cardna-iOS/Cardna-iOS/Source/Scene/MyPageSetting/MyPageSetting.storyboard
Cardna-iOS/Cardna-iOS/Source/Scene/MyPageSetting/MyPageSettingViewController.swift

closed #260 
backButton 안눌리는 hotfix 수정

[#260] backButton 안눌리는 hotfix 수정

---

Cardna-iOS/Cardna-iOS/Source/Scene/Card/Card.storyboard
Cardna-iOS/Cardna-iOS/Source/Scene/Card/CardViewController.swift
Cardna-iOS/Cardna-iOS/Source/Scene/CardNotYetBox/CardNotYetBox.storyboard
Cardna-iOS/Cardna-iOS/Source/Scene/Insight/Insight.storyboard
Cardna-iOS/Cardna-iOS/Source/Scene/MyPageSetting/MyPageSettingRules.storyboard
Cardna-iOS/Cardna-iOS/Source/Scene/SelectCard/SelectCard.storyboard

[#207] 레이아웃 마진값 대거 수정 완료

---

Cardna-iOS/Cardna-iOS/Info.plist
Cardna-iOS/Cardna-iOS/Source/Scene/AddCard/AddCardViewController.swift

closed #263 
카드나 작성 시 이미지/키워드/본문 3가지 중 하나라도 비어있다면 저장이 되지 않고 팝업창이 뜨도록 처리하였습니다.

[#263] 카드나 작성 이미지 있어야만 작성완료 버튼 누르기

---

Cardna-iOS/Cardna-iOS/Source/Scene/Home/HomeViewController.swift

[#181] 홈 empty 라벨

---

Cardna-iOS/Cardna-iOS.xcodeproj/project.pbxproj
Cardna-iOS/Cardna-iOS/Source/Scene/Card/Cell/CardEmptyCollectionViewCell.swift
Cardna-iOS/Cardna-iOS/Source/Scene/Card/Cell/CardEmptyCollectionViewCell.xib

[#221] 파일 추가

---

Cardna-iOS/Cardna-iOS/Source/Scene/CardDetail/CardDetail.storyboard
Cardna-iOS/Cardna-iOS/Source/Scene/CardDetail/CardDetailViewController.swift

[#268] font color 적용

---

Cardna-iOS/Cardna-iOS/Source/Scene/AddCard/AddCardBottomSheetViewController.swift
Cardna-iOS/Cardna-iOS/Source/Scene/AddCard/AddCardViewController.swift
Cardna-iOS/Cardna-iOS/Source/Scene/AddCard/Extensions/AddCardBottomSheetViewController+Extension.swift
Cardna-iOS/Cardna-iOS/Source/Scene/Card/CardBottomSheetViewController.swift
Cardna-iOS/Cardna-iOS/Source/Scene/Card/CardViewController.swift

#239 
화면전환을 present에서 navigationController의 push로 변경하였습니다.
이후 카드나 작성 뷰에서 이미지 선택 오류사항을 Fix하였습니다.

[#239] navigationController로 변경, 카드나 작성 이미지 선택 오류 Fix

---

Cardna-iOS/Cardna-iOS/Source/Scene/AddCard/AddCardCompletedViewController.swift
Cardna-iOS/Cardna-iOS/Source/Scene/AddCard/AddCardViewController.swift

#239 
카드나 작성 완료 후 카드팩으로 이동 처리가 완료되었습니다.

[#239] 카드나 작성 완료 후 카드팩으로 이동

---

Cardna-iOS/Cardna-iOS/Source/Scene/EmailSearch/EmailSearch.storyboard

[#277] 사진 이미지 꽉차게 수정

---

Cardna-iOS/Cardna-iOS/Source/AppSources/AppXibs/ProfileCollectionViewCell.xib
Cardna-iOS/Cardna-iOS/Source/Scene/CardDetail/CardDetailViewController.swift
Cardna-iOS/Cardna-iOS/Source/Scene/MyPage/MyPage.storyboard

[#278] 초기 데이터 비움

---

Cardna-iOS/Cardna-iOS/Source/Scene/AddCard/AddCardViewController.swift
Cardna-iOS/Cardna-iOS/Source/Scene/AddCard/AddCardYouViewController.swift
Cardna-iOS/Cardna-iOS/Source/Scene/Home/HomeViewController.swift

closed #239 
카드너(타인 소개 작성) 완료 후 카드팩으로 이동 처리를 완료하였습니다.

[#239] 카드너 작성 완료 후 카드팩으로 이동 처리

---

Cardna-iOS/Cardna-iOS/Network/APIServices/MainCardAPI/MainCardService.swift
Cardna-iOS/Cardna-iOS/Source/Scene/Home/HomeViewController.swift

[#282] 홈 404 예외처리

---

Cardna-iOS/Cardna-iOS/Source/Scene/Card/CardBottomSheetViewController.swift
Cardna-iOS/Cardna-iOS/Source/Scene/Card/CardViewController.swift

closed #270 
모달에서 카드화 되지 않은 메시지 보관함으로 이동하는 기능을 처리하였습니다.

[#270] 모달에서 카드화 되지 않은 메시지창으로 이동 처리

---

Cardna-iOS/Cardna-iOS/Source/Scene/Card/Cell/CardContainerCollectionViewCell.swift
Cardna-iOS/Cardna-iOS/Source/Scene/Card/Cell/CardEmptyCollectionViewCell.swift
Cardna-iOS/Cardna-iOS/Source/Scene/Card/Cell/CardEmptyCollectionViewCell.xib

[#276] Cell 파일 토대

---

Cardna-iOS/Cardna-iOS/Info.plist
Cardna-iOS/Cardna-iOS/Source/Scene/Card/Cell/CardContainerCollectionViewCell.swift

[#274] Dark mode 막기

---

Cardna-iOS/Cardna-iOS/Configuration/Supports/AppDelegate.swift

[#287] 가로모드 막기

---

Cardna-iOS/Cardna-iOS/Source/Scene/Card/Cell/CardEmptyCollectionViewCell.swift
Cardna-iOS/Cardna-iOS/Source/Scene/Card/Cell/CardEmptyCollectionViewCell.xib

closed #289 
엠티 뷰를 만들었고.. (4개)
상황에 따라서 아직 적용은 안해줬음..!..

[#289] 카드팩 empty view layout 구현
